layout_spectrum: 0.6469534
typography_spectrum: 0.9193549
color:
  saturation: 0.2365299
  lightness: 0.4229375
  brandStrength: 0.9784946
  brandColors:
    - '#181516'
    - '#D9DEDE'
    - '#6E8839'
    - '#A32027'
    - '#D89B77'
  rhythmicContrast: 0.2556033
name: Block Consult
